[workspace]
members = ["crates/lucky", "crates/config"]
default_members = ["crates/lucky"]
resolver = "2"

[workspace.dependencies]
config = { path = "crates/config" }

tracing = "0.1.40"
tracing-subscriber = "0.3.18"
anyhow = "1.0.81"
