leader = "Mod1"
workspaces = 10

border_width = 4
border_color = "#252525"
active_border_color = "#ff0000"
focus_new_clients = true

[[actions]]
modifiers = ["Leader"]
key = "q"
action = "Close"

[[commands]]
modifiers = ["Leader"]
key = "Enter"
command = "alacritty"

[[commands]]
modifiers = ["Leader"]
key = "d"
command = "wezterm"
