leader = "Mod1"
workspaces = 10

border_width = 4
border_color = "#252525"
active_border_color = "#2D4F67"
focus_new_clients = true

[[actions]]
modifiers = ["Leader"]
key = "q"
action = "Close"

[[actions]]
modifiers = ["Leader", "Shift"]
key = "r"
action = "Reload"

[[actions]]
modifiers = ["Leader"]
key = "h"
action = "FocusLeft"

[[actions]]
modifiers = ["Leader"]
key = "j"
action = "FocusDown"

[[actions]]
modifiers = ["Leader"]
key = "k"
action = "FocusUp"

[[actions]]
modifiers = ["Leader"]
key = "l"
action = "FocusRight"

[[actions]]
modifiers = ["Leader", "Shift"]
key = "h"
action = "MoveLeft"

[[actions]]
modifiers = ["Leader", "Shift"]
key = "j"
action = "MoveDown"

[[actions]]
modifiers = ["Leader", "Shift"]
key = "k"
action = "MoveUp"

[[actions]]
modifiers = ["Leader", "Shift"]
key = "l"
action = "MoveRight"

[[commands]]
modifiers = ["Leader"]
key = "Enter"
command = "wezterm"

[[commands]]
modifiers = ["Leader"]
key = "d"
command = "rofi -show drun"
