leader = "Mod1"
workspaces = 10

border_width = 10

[[actions]]
modifiers = ["Leader"]
key = "q"
action = "Close"

[[commands]]
modifiers = ["Leader"]
key = "Enter"
command = "wezterm"

[[commands]]
modifiers = ["Control"]
key = "Enter"
command = "alacritty"
