leader = "Mod1"
workspaces = 10

border_width = 23
border_color = "#252525"

[[actions]]
modifiers = ["Leader"]
key = "q"
action = "Close"

[[commands]]
modifiers = ["Leader"]
key = "Enter"
command = "alacritty"

[[commands]]
modifiers = ["Leader"]
key = "d"
command = "thunar"
